### ISSUE TITLE
Error "Unhandled promise rejection" on webdriver libs - Cannot read property 'destUrl' of null

### ISSUE THREAD

**Issue by SebastianChece2389** [AlexanderMoskovkin/saucelabs-connector#37]
Hello,

we have randomly an error when testing on saucelabs by using "testcafe-browser-provider-saucelabs" which is using "saucelabs-connector". It seems to have nothing to do with our test code. It also happens sporadically and the error is in the webdriver libs, which are called by "saucelabs-connector".

Error:
  ```
1) Unhandled promise rejection:
             Error: [eval("")] Error response status: 17, , JavaScriptError -
       An error occurred while executing user supplied JavaScript. Selenium
       error: javascript error: Cannot read property 'destUrl' of null
       (Session info: chrome=83.0.4103.61)
       (Driver info: chromedriver=83.0.4103.39
  
   (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Windows
       NT 10.0.10586 x86_64)
       at exports.newError
       (/home/circleci/project/node_modules/wd/lib/utils.js:152:13)
       at /home/circleci/project/node_modules/wd/lib/callbacks.js:94:19
       at /home/circleci/project/node_modules/wd/lib/webdriver.js:202:5
       at Request._callback
       (/home/circleci/project/node_modules/wd/lib/http-utils.js:89:7)
       at Request.self.callback
       (/home/circleci/project/node_modules/request/request.js:185:22)
       at Request.emit (events.js:198:13)
       at Request.EventEmitter.emit (domain.js:448:20)
       at Request.<anonymous>
       (/home/circleci/project/node_modules/request/request.js:1161:10)
       at Request.emit (events.js:198:13)
       at Request.EventEmitter.emit (domain.js:448:20)
       Browser: Chrome 83.0.4103.61 / Windows 10
       (https://app.************.saucelabs.com/tests/0b17c28b60594e07a73b1646a95abdff)
```
Most important: 
Unhandled promise rejection
...
Cannot read property 'destUrl' of null
...
node_modules/wd/lib/utils.j

wd = webdriver is used by "saucelabs-connector" and we think the code part which can lead to this problems is in file
 https://github.com/DevExpress/saucelabs-connector/blob/f76536d37212b0a6ff2207962ed255906608d478/src/index.js
on this code blocks, it seems it occurs when saucelabs is not answering or too late answering and promise is not resolved. On pingIntervalId and later calling getSessionUrl(webDriver)

```
async startBrowser (browser, url, { jobName, tags, build } = {}, timeout = null) {
        var webDriver = wd.promiseChainRemote(`ondemand.${SAUCE_API_HOST}`, 80, this.username, this.accessKey);

        var pingWebDriver = () => webDriver.eval('');

        webDriver.once('status', () => {
            // HACK: if the webDriver doesn't get any command within 1000s, it fails
            // with the timeout error. We should send any command to avoid this.
            **webDriver.pingIntervalId = setInterval(pingWebDriver, WEB_DRIVER_PING_INTERVAL);**

            if (this.options.connectorLogging) {
                this
                    .getSessionUrl(webDriver)
                    .then(sessionUrl => this._log(`${browser.browserName} started. See ${sessionUrl}`));
            }
        });
```

Do you have any idea how and why this error could hapenning and how to fix it?

Best regards and thanks a lot
Sebastian

**Comment by SebastianChece2389** [comment]
Some minutes ago, same error again. This time another browser, edge instead of chrome. 
Just to show that it is not browser related.

   ```
Error: [eval("")] Error response status: 17, , JavaScriptError -
       An error occurred while executing user supplied JavaScript. Selenium
       error: javascript error: Cannot read property 'destUrl' of null
       (Session info: MicrosoftEdge=83.0.478.37)
       (Driver info: msedgedriver=83.0.478.37
       (7feb1dfc5bdafe8eb783cb5244c5af8f66fc87d0),platform=Windows NT
       10.0.10586 x86_64)
       at exports.newError
       (/home/circleci/project/node_modules/wd/lib/utils.js:152:13)
       at /home/circleci/project/node_modules/wd/lib/callbacks.js:94:19
       at /home/circleci/project/node_modules/wd/lib/webdriver.js:202:5
       at Request._callback
       (/home/circleci/project/node_modules/wd/lib/http-utils.js:89:7)
       at Request.self.callback
       (/home/circleci/project/node_modules/request/request.js:185:22)
       at Request.emit (events.js:198:13)
       at Request.EventEmitter.emit (domain.js:448:20)
       at Request.<anonymous>
       (/home/circleci/project/node_modules/request/request.js:1161:10)
       at Request.emit (events.js:198:13)
       at Request.EventEmitter.emit (domain.js:448:20)
```

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. Unfortunately, I cannot reproduce the issue. Could you please provide an example project that I can use to reproduce and debug the problem?
